const std = @import("std");
const postgres = @import("../../../postgres.zig");
const stable_score = @import("../../../stable_score.zig");
const lazer = @import("../../../lazer.zig");
const r2 = @import("../../../r2.zig");
const stable_client = @import("../../../stable_client.zig");
const postgres_stable_sessions = @import("../../../postgres_stable_sessions.zig");
const database_sql = @import("database_sql");
const common = @import("../common.zig");
const pg_score_maintenance = @import("../scores/maintenance.zig");

const StableScoreGraceResult = postgres_stable_sessions.GraceResult;
const schema_version = common.schema_version;

pub fn bindObjectStorage(self: anytype, object_store: r2.Storage) void {
    self.object_store = object_store;
}

pub fn close(self: anytype) void {
    self.pool.deinit();
}

pub fn rotateStableScoreSession(self: anytype, user_id: i32, token: []const u8, binding: stable_client.Binding, now: i64, grace_seconds: i64) !void {
    return postgres_stable_sessions.rotate(self.allocator, &self.pool, user_id, token, binding, now, grace_seconds);
}

pub fn consumeStableScoreGrace(self: anytype, token: []const u8, user_id: i32, binding: stable_client.Binding, submission_checksum: []const u8, now: i64) !StableScoreGraceResult {
    return postgres_stable_sessions.consume(self.allocator, &self.pool, token, user_id, binding, submission_checksum, now);
}

pub fn revokeStableScoreSessionsForUser(self: anytype, user_id: i32) !usize {
    return postgres_stable_sessions.revoke(self.allocator, &self.pool, user_id, std.Io.Clock.real.now(self.io).toSeconds());
}

pub fn refreshExternalOnly(self: anytype, conn: *postgres.c.PGconn) !void {
    var result = try postgres.query(conn, "SELECT count(*) FROM information_schema.columns WHERE table_schema='zigcho' AND is_nullable='YES' AND ((table_name='beatmap_archives' AND column_name='osz_file') OR (table_name='beatmap_media' AND column_name='data'))");
    defer result.deinit();
    self.external_only = try result.int(i32, 0, 0) == 2;
}

pub fn migrate(self: anytype) !void {
    var lease = self.pool.acquire();
    defer lease.release();
    var exists = try postgres.query(lease.conn, "SELECT (to_regclass('zigcho.schema_migrations') IS NOT NULL)::int");
    const bootstrapped = try exists.int(i32, 0, 0) == 0;
    exists.deinit();
    if (bootstrapped) {
        try postgres.exec(lease.conn, "BEGIN;" ++ database_sql.postgres_schema ++ "COMMIT;");
        try refreshExternalOnly(self, lease.conn);
        return;
    }
    var result = try postgres.query(lease.conn, "SELECT max(version) FROM zigcho.schema_migrations");
    if (result.rows() == 0 or result.isNull(0, 0)) {
        result.deinit();
        return error.UnsupportedSchemaVersion;
    }
    const version = try result.int(i32, 0, 0);
    result.deinit();
    if (version == 12) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "CREATE TABLE zigcho.chat_messages(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,sender_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,target text NOT NULL,message text NOT NULL,created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint));" ++
                "CREATE INDEX chat_messages_target_time ON zigcho.chat_messages(target,created_at DESC);" ++
                "CREATE INDEX chat_messages_sender_time ON zigcho.chat_messages(sender_id,created_at DESC);" ++
                "CREATE TABLE zigcho.chat_channels(name text PRIMARY KEY,topic text NOT NULL,write_privileges bigint NOT NULL DEFAULT 1,locked boolean NOT NULL DEFAULT false,updated_by integer,updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint));" ++
                "INSERT INTO zigcho.chat_channels(name,topic,write_privileges) VALUES('#osu','general chat',1),('#announce','updates',8192),('#lobby','multiplayer lobby',1),('#lazer','lazer chat',1);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(13);" ++
                "COMMIT",
        );
    } else if (version < 13 or version > schema_version) return error.UnsupportedSchemaVersion;
    if (version <= 13) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "ALTER TABLE zigcho.beatmaps ADD COLUMN status_frozen boolean NOT NULL DEFAULT false;" ++
                "CREATE TABLE zigcho.beatmap_rank_requests(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,set_id integer NOT NULL,map_id integer NOT NULL REFERENCES zigcho.beatmaps(id) ON DELETE CASCADE,requester_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,active boolean NOT NULL DEFAULT true,created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),resolved_at bigint);" ++
                "CREATE UNIQUE INDEX beatmap_rank_requests_active_user ON zigcho.beatmap_rank_requests(set_id,requester_id) WHERE active;" ++
                "CREATE INDEX beatmap_rank_requests_queue ON zigcho.beatmap_rank_requests(active,created_at,set_id);" ++
                "CREATE TABLE zigcho.beatmap_nominations(set_id integer NOT NULL,nominator_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,active boolean NOT NULL DEFAULT true,created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),PRIMARY KEY(set_id,nominator_id));" ++
                "CREATE INDEX beatmap_nominations_active ON zigcho.beatmap_nominations(set_id,active);" ++
                "CREATE TABLE zigcho.beatmap_rank_events(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,set_id integer NOT NULL,actor_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE RESTRICT,action text NOT NULL,from_status smallint NOT NULL,to_status smallint NOT NULL,reason text NOT NULL,created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint));" ++
                "CREATE INDEX beatmap_rank_events_set_time ON zigcho.beatmap_rank_events(set_id,created_at DESC,id DESC);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(14);" ++
                "COMMIT",
        );
    }
    if (version <= 14) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "CREATE TABLE zigcho.moderation_appeals(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,kind text NOT NULL CHECK(kind IN ('restriction','hwid')),message text NOT NULL,status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','accepted','denied')),reviewer_id integer REFERENCES zigcho.users(id) ON DELETE SET NULL,resolution text,created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),resolved_at bigint);" ++
                "CREATE UNIQUE INDEX moderation_appeals_one_open ON zigcho.moderation_appeals(user_id,kind) WHERE status='open';" ++
                "CREATE INDEX moderation_appeals_queue ON zigcho.moderation_appeals(status,created_at,id);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(15);" ++
                "COMMIT",
        );
    }
    if (version <= 15) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "CREATE TABLE zigcho.score_pins(user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,score_id bigint NOT NULL UNIQUE REFERENCES zigcho.scores(id) ON DELETE CASCADE,pinned_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),PRIMARY KEY(user_id,score_id));" ++
                "CREATE INDEX score_pins_user_time ON zigcho.score_pins(user_id,pinned_at DESC,score_id DESC);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(16);" ++
                "COMMIT",
        );
    }
    if (version <= 16) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "ALTER TABLE zigcho.beatmap_archives ADD COLUMN last_accessed_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint);" ++
                "UPDATE zigcho.beatmap_archives SET last_accessed_at=imported_at;" ++
                "CREATE INDEX beatmap_archives_lru ON zigcho.beatmap_archives(last_accessed_at,imported_at,set_id);" ++
                "CREATE TABLE zigcho.beatmap_hydration_failures(md5 char(32) PRIMARY KEY,set_id integer NOT NULL,attempts smallint NOT NULL DEFAULT 1 CHECK(attempts BETWEEN 1 AND 32),next_retry_at bigint NOT NULL,last_error text NOT NULL,updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint));" ++
                "CREATE INDEX beatmap_hydration_retry ON zigcho.beatmap_hydration_failures(next_retry_at,updated_at);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(17);" ++
                "COMMIT",
        );
    }
    if (version <= 17) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "CREATE TABLE zigcho.screenshots(token char(8) PRIMARY KEY,extension text NOT NULL CHECK(extension IN ('jpeg','png')),uploader_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,image bytea NOT NULL CHECK(octet_length(image)<=4194304),created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint));" ++
                "CREATE INDEX screenshots_uploader_time ON zigcho.screenshots(uploader_id,created_at DESC);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(18);" ++
                "COMMIT",
        );
    }
    if (version <= 18) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "CREATE TABLE zigcho.beatmap_media(set_id integer NOT NULL,kind text NOT NULL CHECK(kind IN ('cover','cover_2x','card','card_2x','list','list_2x','slimcover','slimcover_2x','thumb','thumb_large','preview')),content_type text NOT NULL CHECK(content_type IN ('image/jpeg','audio/ogg','audio/mpeg')),sha256 char(64) NOT NULL,data bytea NOT NULL CHECK(octet_length(data) BETWEEN 1 AND 4194304),fetched_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),last_accessed_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),PRIMARY KEY(set_id,kind));" ++
                "CREATE INDEX beatmap_media_lru ON zigcho.beatmap_media(last_accessed_at,fetched_at,set_id,kind);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(19);" ++
                "COMMIT",
        );
    }
    if (version <= 19) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "CREATE TABLE zigcho.beatmap_comments(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,target_id bigint NOT NULL,target_type text NOT NULL CHECK(target_type IN ('song','map','replay')),user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,time double precision NOT NULL,comment text NOT NULL CHECK(length(comment) BETWEEN 1 AND 80),colour char(6),created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint));" ++
                "CREATE INDEX beatmap_comments_target ON zigcho.beatmap_comments(target_type,target_id,id);" ++
                "CREATE TABLE zigcho.direct_messages(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,from_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,to_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,message text NOT NULL CHECK(length(message) BETWEEN 1 AND 2000),read boolean NOT NULL DEFAULT false,created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint));" ++
                "CREATE INDEX direct_messages_unread ON zigcho.direct_messages(to_id,read,created_at,id);" ++
                "CREATE INDEX direct_messages_conversation ON zigcho.direct_messages(to_id,from_id,read,id);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(20);" ++
                "COMMIT",
        );
    }
    if (version <= 20) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "ALTER TABLE zigcho.lazer_scores ADD COLUMN rank text NOT NULL DEFAULT 'F';" ++
                "ALTER TABLE zigcho.lazer_scores ADD COLUMN maximum_statistics_json jsonb NOT NULL DEFAULT '{}'::jsonb;" ++
                "ALTER TABLE zigcho.lazer_scores ADD COLUMN pauses_json jsonb NOT NULL DEFAULT '[]'::jsonb;" ++
                "CREATE TABLE zigcho.lazer_score_tokens(id bigint PRIMARY KEY,user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,beatmap_id integer NOT NULL REFERENCES zigcho.beatmaps(id) ON DELETE CASCADE,beatmap_hash char(32) NOT NULL,ruleset_id smallint NOT NULL CHECK(ruleset_id BETWEEN 0 AND 3),version_hash char(32) NOT NULL,created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),expires_at bigint NOT NULL,consumed_at bigint,score_id bigint REFERENCES zigcho.lazer_scores(id) ON DELETE SET NULL);" ++
                "CREATE INDEX lazer_score_tokens_user_expiry ON zigcho.lazer_score_tokens(user_id,expires_at DESC);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(21);" ++
                "COMMIT",
        );
    }
    if (version <= 21) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "ALTER TABLE zigcho.lazer_scores ADD COLUMN pp double precision NOT NULL DEFAULT 0;" ++
                "ALTER TABLE zigcho.lazer_scores ADD COLUMN best boolean NOT NULL DEFAULT false;" ++
                "WITH ranked AS (SELECT id,row_number() OVER (PARTITION BY user_id,beatmap_id,ruleset_id,rank_namespace ORDER BY pp DESC,total_score DESC,id ASC) place FROM zigcho.lazer_scores WHERE passed) UPDATE zigcho.lazer_scores scores SET best=true FROM ranked WHERE scores.id=ranked.id AND ranked.place=1;" ++
                "CREATE INDEX lazer_scores_user_best ON zigcho.lazer_scores(user_id,ruleset_id,rank_namespace,beatmap_id,best);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(22);" ++
                "COMMIT",
        );
    }
    if (version <= 22) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "ALTER TABLE zigcho.users ADD COLUMN bio text NOT NULL DEFAULT '' CHECK(length(bio)<=500);" ++
                "ALTER TABLE zigcho.users ADD COLUMN preferred_mode smallint NOT NULL DEFAULT 0 CHECK(preferred_mode BETWEEN 0 AND 3);" ++
                "ALTER TABLE zigcho.users ADD COLUMN profile_source text NOT NULL DEFAULT 'all' CHECK(profile_source IN('all','lazer','scorev2'));" ++
                "CREATE TABLE zigcho.user_avatars(user_id integer PRIMARY KEY REFERENCES zigcho.users(id) ON DELETE CASCADE,object_key text NOT NULL UNIQUE CHECK(length(object_key) BETWEEN 1 AND 200),content_type text NOT NULL CHECK(content_type IN('image/png','image/jpeg','image/gif')),etag char(64) NOT NULL,updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint));" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(23);" ++
                "COMMIT",
        );
    }
    if (version <= 23) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "ALTER TABLE zigcho.users ADD COLUMN profile_title text NOT NULL DEFAULT '' CHECK(length(profile_title)<=40);" ++
                "ALTER TABLE zigcho.users ADD COLUMN profile_pronouns text NOT NULL DEFAULT '' CHECK(length(profile_pronouns)<=32);" ++
                "ALTER TABLE zigcho.users ADD COLUMN profile_location text NOT NULL DEFAULT '' CHECK(length(profile_location)<=60);" ++
                "ALTER TABLE zigcho.users ADD COLUMN profile_website text NOT NULL DEFAULT '' CHECK(length(profile_website)<=200);" ++
                "ALTER TABLE zigcho.users ADD COLUMN profile_accent text NOT NULL DEFAULT 'pink' CHECK(profile_accent IN('pink','violet','blue','mint','gold','red'));" ++
                "ALTER TABLE zigcho.users ADD COLUMN show_country boolean NOT NULL DEFAULT true;" ++
                "ALTER TABLE zigcho.users ADD COLUMN show_profile_stats boolean NOT NULL DEFAULT true;" ++
                "ALTER TABLE zigcho.users ADD COLUMN show_recent_scores boolean NOT NULL DEFAULT true;" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(24);" ++
                "COMMIT",
        );
    }
    if (version <= 24) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "CREATE TABLE zigcho.anticheat_observations(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,score_id bigint REFERENCES zigcho.scores(id) ON DELETE SET NULL,source text NOT NULL CHECK(source IN('stable_login','stable_lastfm','stable_score')),module text NOT NULL CHECK(length(module) BETWEEN 1 AND 64),action smallint NOT NULL CHECK(action BETWEEN 0 AND 3),sample_weight integer NOT NULL DEFAULT 1 CHECK(sample_weight BETWEEN 1 AND 100000),reason integer NOT NULL,risk_score smallint NOT NULL CHECK(risk_score BETWEEN 0 AND 1000),confidence_bps integer NOT NULL CHECK(confidence_bps BETWEEN 0 AND 10000),evidence bigint NOT NULL DEFAULT 0 CHECK(evidence>=0),decision_flags bigint NOT NULL DEFAULT 0 CHECK(decision_flags>=0),rule_revision integer NOT NULL DEFAULT 0,objects_checked integer NOT NULL DEFAULT 0 CHECK(objects_checked>=0),matched_clicks integer NOT NULL DEFAULT 0 CHECK(matched_clicks BETWEEN 0 AND objects_checked),mean_abs_timing_error_milli integer NOT NULL DEFAULT 0 CHECK(mean_abs_timing_error_milli>=0),timing_stddev_milli integer NOT NULL DEFAULT 0 CHECK(timing_stddev_milli>=0),exact_timing_bps integer NOT NULL DEFAULT 0 CHECK(exact_timing_bps BETWEEN 0 AND 10000),center_hits_bps integer NOT NULL DEFAULT 0 CHECK(center_hits_bps BETWEEN 0 AND 10000),mean_center_distance_milli integer NOT NULL DEFAULT 0 CHECK(mean_center_distance_milli>=0),snap_events integer NOT NULL DEFAULT 0 CHECK(snap_events BETWEEN 0 AND objects_checked),review_label text NOT NULL DEFAULT 'pending' CHECK(review_label IN('pending','clean','uncertain','cheat','dismissed')),reviewer_id integer REFERENCES zigcho.users(id) ON DELETE SET NULL,review_note text NOT NULL DEFAULT '' CHECK(length(review_note)<=1000),reviewed_at bigint,created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),CHECK((review_label='pending' AND reviewer_id IS NULL AND reviewed_at IS NULL AND review_note='') OR (review_label!='pending' AND reviewer_id IS NOT NULL AND reviewed_at IS NOT NULL AND length(review_note) BETWEEN 3 AND 1000)));" ++
                "CREATE UNIQUE INDEX anticheat_observations_score ON zigcho.anticheat_observations(score_id) WHERE score_id IS NOT NULL;" ++
                "CREATE INDEX anticheat_observations_queue ON zigcho.anticheat_observations(review_label,created_at,id);" ++
                "CREATE INDEX anticheat_observations_user ON zigcho.anticheat_observations(user_id,created_at DESC,id DESC);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(25);" ++
                "COMMIT",
        );
    }
    if (version <= 25) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "ALTER TABLE zigcho.anticheat_observations ADD COLUMN replay_match_count integer NOT NULL DEFAULT 0 CHECK(replay_match_count BETWEEN 0 AND 100000),ADD COLUMN key_press_count integer NOT NULL DEFAULT 0 CHECK(key_press_count>=0),ADD COLUMN key_hold_count integer NOT NULL DEFAULT 0 CHECK(key_hold_count BETWEEN 0 AND key_press_count),ADD COLUMN mean_hold_duration_milli integer NOT NULL DEFAULT 0 CHECK(mean_hold_duration_milli>=0),ADD COLUMN hold_duration_stddev_milli integer NOT NULL DEFAULT 0 CHECK(hold_duration_stddev_milli>=0),ADD COLUMN alternation_bps integer NOT NULL DEFAULT 0 CHECK(alternation_bps BETWEEN 0 AND 10000),ADD COLUMN target_distance_stddev_milli integer NOT NULL DEFAULT 0 CHECK(target_distance_stddev_milli>=0),ADD COLUMN velocity_spike_count integer NOT NULL DEFAULT 0 CHECK(velocity_spike_count>=0),ADD COLUMN movement_velocity_stddev_milli integer NOT NULL DEFAULT 0 CHECK(movement_velocity_stddev_milli>=0);" ++
                "CREATE TABLE zigcho.anticheat_replay_fingerprints(score_id bigint PRIMARY KEY REFERENCES zigcho.scores(id) ON DELETE CASCADE,user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,replay_sha256 bytea NOT NULL CHECK(octet_length(replay_sha256)=32),created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint));" ++
                "CREATE INDEX anticheat_replay_fingerprints_hash ON zigcho.anticheat_replay_fingerprints(replay_sha256,user_id);" ++
                "CREATE INDEX anticheat_replay_fingerprints_user ON zigcho.anticheat_replay_fingerprints(user_id,created_at DESC,score_id DESC);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(26);" ++
                "COMMIT",
        );
    }
    if (version <= 26) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "ALTER TABLE zigcho.chat_messages ADD COLUMN is_action boolean NOT NULL DEFAULT false;" ++
                "ALTER TABLE zigcho.chat_messages ADD COLUMN client_uuid text NOT NULL DEFAULT '' CHECK(length(client_uuid) IN(0,36));" ++
                "CREATE UNIQUE INDEX chat_messages_sender_uuid ON zigcho.chat_messages(sender_id,client_uuid) WHERE client_uuid!='';" ++
                "CREATE TABLE zigcho.lazer_channel_reads(user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,channel_id smallint NOT NULL CHECK(channel_id BETWEEN 1 AND 4),last_read_id bigint NOT NULL DEFAULT 0,updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),PRIMARY KEY(user_id,channel_id));" ++
                "CREATE TABLE zigcho.user_blocks(user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,blocked_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),PRIMARY KEY(user_id,blocked_id),CHECK(user_id!=blocked_id));" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(27);" ++
                "COMMIT",
        );
    }
    if (version <= 27) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "ALTER TABLE zigcho.direct_messages ADD COLUMN is_action boolean NOT NULL DEFAULT false,ADD COLUMN client_uuid text NOT NULL DEFAULT '';" ++
                "CREATE UNIQUE INDEX direct_messages_sender_uuid ON zigcho.direct_messages(from_id,client_uuid) WHERE client_uuid!='';" ++
                "UPDATE zigcho.custom_mods SET ranked=true;" ++
                "CREATE TABLE zigcho.user_achievements(user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,achievement_id smallint NOT NULL CHECK(achievement_id>0),score_source text NOT NULL CHECK(score_source IN ('stable','lazer')),score_id bigint NOT NULL CHECK(score_id>0),achieved_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),PRIMARY KEY(user_id,achievement_id));" ++
                "CREATE INDEX user_achievements_score ON zigcho.user_achievements(score_source,score_id);" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(28);" ++
                "COMMIT",
        );
        try pg_score_maintenance.rebuildRankedStats(self, lease.conn, true);
    }
    if (version <= 28) {
        try postgres.exec(
            lease.conn,
            "BEGIN;" ++
                "ALTER TABLE zigcho.scores ADD COLUMN star_rating double precision NOT NULL DEFAULT 0;" ++
                "ALTER TABLE zigcho.lazer_scores ADD COLUMN star_rating double precision NOT NULL DEFAULT 0;" ++
                "UPDATE zigcho.scores s SET star_rating=coalesce(b.star_rating,0) FROM zigcho.beatmaps b WHERE b.md5=s.map_md5;" ++
                "UPDATE zigcho.lazer_scores s SET star_rating=coalesce(b.star_rating,0) FROM zigcho.beatmaps b WHERE b.id=s.beatmap_id;" ++
                "INSERT INTO zigcho.schema_migrations(version) VALUES(29);" ++
                "COMMIT",
        );
    }
    if (version <= 30) try postgres.exec(lease.conn, database_sql.postgresMigration(31));
    if (version <= 31) try postgres.exec(lease.conn, database_sql.postgresMigration(32));
    if (version <= 32) try postgres.exec(lease.conn, database_sql.postgresMigration(33));
    if (version <= 33) try postgres.exec(lease.conn, database_sql.postgresMigration(34));
    if (version <= 34) try postgres.exec(lease.conn, database_sql.postgresMigration(35));
    if (version <= 35) try postgres.exec(lease.conn, database_sql.postgresMigration(36));
    if (version <= 36) try postgres.exec(lease.conn, database_sql.postgresMigration(37));
    if (version <= 37) try postgres.exec(lease.conn, database_sql.postgresMigration(38));
    if (version <= 38) try postgres.exec(lease.conn, database_sql.postgresMigration(39));
    if (version <= 39) try postgres.exec(lease.conn, database_sql.postgresMigration(40));
    if (version <= 40) try postgres.exec(lease.conn, database_sql.postgresMigration(41));
    if (version <= 41) try postgres.exec(lease.conn, database_sql.postgresMigration(42));
    if (version <= 42) try postgres.exec(lease.conn, database_sql.postgresMigration(43));
    if (version <= 43) try postgres.exec(lease.conn, database_sql.postgresMigration(44));
    if (version <= 44) try postgres.exec(lease.conn, database_sql.postgresMigration(45));
    if (version <= 45) try postgres.exec(lease.conn, database_sql.postgresMigration(46));
    if (version <= 46) try postgres.exec(lease.conn, database_sql.postgresMigration(47));
    if (version <= 47) try postgres.exec(lease.conn, database_sql.postgresMigration(48));
    if (version <= 48) try postgres.exec(lease.conn, database_sql.postgresMigration(49));
    try pg_score_maintenance.backfillLazerClassicScoresWithConnection(self, lease.conn);
    try finishPendingRankedStatsRebuild(self, lease.conn);
    try postgres.exec(lease.conn, "DELETE FROM zigcho.user_stats_history WHERE day<((extract(epoch FROM clock_timestamp())::bigint/86400)-89)*86400");
    try refreshExternalOnly(self, lease.conn);
    try postgres.exec(
        lease.conn,
        "BEGIN;" ++
            "UPDATE zigcho.lazer_scores SET best=false;" ++
            "WITH ordered AS (SELECT id,row_number() OVER(PARTITION BY user_id,beatmap_id,ruleset_id,rank_namespace ORDER BY pp DESC,total_score DESC,id ASC) place FROM zigcho.lazer_scores WHERE passed) " ++
            "UPDATE zigcho.lazer_scores scores SET best=true FROM ordered WHERE scores.id=ordered.id AND ordered.place=1;" ++
            "COMMIT",
    );
    try postgres.exec(lease.conn, "INSERT INTO zigcho.chat_channels(name,topic,write_privileges) VALUES('#osu','general chat',1),('#announce','updates',8192),('#lobby','multiplayer lobby',1),('#lazer','lazer chat',1) ON CONFLICT(name) DO NOTHING");
}

pub fn finishPendingRankedStatsRebuild(self: anytype, conn: *postgres.c.PGconn) !void {
    try postgres.exec(conn, "BEGIN");
    errdefer postgres.exec(conn, "ROLLBACK") catch {};
    try pg_score_maintenance.history_updates.lockMaintenance(conn);
    var marker = try postgres.query(conn, "SELECT key FROM zigcho.maintenance_markers WHERE key='schema46_ranked_stats_rebuild' FOR UPDATE");
    defer marker.deinit();
    if (marker.rows() != 0) {
        try pg_score_maintenance.rebuildRankedStats(self, conn, false);
        try pg_score_maintenance.recordAllStatsHistoryCurrentWithConnection(self, conn);
        var cleared = try postgres.query(conn, "DELETE FROM zigcho.maintenance_markers WHERE key='schema46_ranked_stats_rebuild' RETURNING 1");
        defer cleared.deinit();
        if (cleared.rows() != 1) return error.DatabaseQueryFailed;
    }
    try postgres.exec(conn, "COMMIT");
}
