BEGIN;
ALTER TABLE zigcho.anticheat_review_exclusions ADD COLUMN skip_checks boolean NOT NULL DEFAULT false;
ALTER TABLE zigcho.anticheat_observations DROP CONSTRAINT anticheat_observations_source_check;
ALTER TABLE zigcho.anticheat_observations ADD CONSTRAINT anticheat_observations_source_check CHECK(source IN ('stable_login','stable_lastfm','stable_score','lazer_score'));
ALTER TABLE zigcho.anticheat_observations ADD COLUMN enforced boolean NOT NULL DEFAULT false;
ALTER TABLE zigcho.anticheat_observations ADD COLUMN lazer_score_id bigint REFERENCES zigcho.lazer_scores(id) ON DELETE SET NULL;
ALTER TABLE zigcho.anticheat_observations ADD CONSTRAINT anticheat_observations_stable_identity CHECK(score_id IS NULL OR (source='stable_score' AND lazer_score_id IS NULL));
ALTER TABLE zigcho.anticheat_observations ADD CONSTRAINT anticheat_observations_lazer_identity CHECK(lazer_score_id IS NULL OR (source='lazer_score' AND score_id IS NULL));
CREATE UNIQUE INDEX anticheat_observations_lazer_score ON zigcho.anticheat_observations(lazer_score_id) WHERE lazer_score_id IS NOT NULL;
CREATE INDEX anticheat_check_exclusions_active ON zigcho.anticheat_review_exclusions(user_id,scope,expires_at) WHERE skip_checks AND revoked_at IS NULL;
INSERT INTO zigcho.schema_migrations(version) VALUES(50);
COMMIT;
